# Generated by Django 4.2.1 on 2023-05-11 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0002_pesananstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesananstatus',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_pesanan_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
