# Generated by Django 4.2.1 on 2023-05-11 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0003_pesananstatus_user_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='payment_status',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_status_pesanan', to='cargo_app.paymentstatus'),
        ),
    ]
