# Generated by Django 4.2.1 on 2023-05-11 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0005_alter_pesanan_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='code',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_status_pesanan', to='cargo_app.paymentstatus', to_field='code'),
        ),
    ]
