# Generated by Django 4.2.1 on 2023-06-27 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0008_alter_pesananstatus_tgl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_pesanan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_status_pesanan', to='cargo_app.paymentstatus'),
        ),
    ]
