# Generated by Django 4.2.1 on 2023-06-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0009_pesanan_user_id_alter_pesanan_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biayajarak',
            name='status',
            field=models.CharField(max_length=70),
        ),
    ]
