# Generated by Django 4.2.1 on 2023-06-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0010_alter_biayajarak_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='biayajarak',
            name='keterangan',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='biayajarak',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=50),
        ),
    ]
