# Generated by Django 4.2.1 on 2023-07-02 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0011_biayajarak_keterangan_alter_biayajarak_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_status_pesanan', to='cargo_app.paymentstatus', to_field='code'),
        ),
    ]
