# Generated by Django 4.2.1 on 2023-07-03 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0012_alter_pesanan_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesanan',
            name='category',
        ),
    ]
