# Generated by Django 4.2.1 on 2023-07-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0014_pesanan_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='placeidlokasiasal',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='placeidlokasitujuan',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='waktu',
            field=models.CharField(max_length=50),
        ),
    ]
